from setuptools import setup, find_packages

setup(
    name="research_dvae",
    version="0.1.0",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    install_requires=[
        "numpy",
        "scipy",
        "pandas",
        "torch",
        "torchaudio",
        "torchvision",
        "audioread",
        "certifi",
        "cffi",
        "charset-normalizer",
        "contourpy",
        "cycler",
        "decorator",
        "filelock",
        "fonttools",
        "fsspec",
        "idna",
        "Jinja2",
        "joblib",
        "kiwisolver",
        "lazy_loader",
        "librosa",
        "llvmlite",
        "MarkupSafe",
        "matplotlib",
        "mpmath",
        "msgpack",
        "networkx",
        "numba",
        "packaging",
        "pillow",
        "platformdirs",
        "plotly",
        "pooch",
        "pycparser",
        "pynndescent",
        "pyparsing",
        "pystoi",
        "python-dateutil",
        "pytz",
        "requests",
        "scikit-learn",
        "seaborn",
        "six",
        "soundfile",
        "soxr",
        "sympy",
        "tenacity",
        "threadpoolctl",
        "tqdm",
        "typing_extensions",
        "tzdata",
        "umap-learn",
        "urllib3",
    ],
    extras_require={
        "dev": [
            "pytest",
            "flake8",
            "black",
            "isort",
            "mypy",
            "pre-commit",
        ],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="Dynamic Variational Autoencoder research project",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/research-DVAE",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
