devices:
  mac_studio:
    matcher:
      type: hostname
      value: Stash-Mac-Studio.local
    saved_root: /Volumes/bucket/DoyaU/stash/research-DVAE/saved_model
    data_dir: /Volumes/bucket/DoyaU/stash/research-DVAE/data
  deigo_cluster:
    matcher:
      type: substring
      value: deigo
    saved_root: /flash/DoyaU/stash/research-DVAE/saved_model
    data_dir: /bucket/DoyaU/stash/research-DVAE/data